# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fbu-project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fbu-project
  pod 'LoremIpsum'
  pod 'Koloda'

  target 'fbu-projectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'fbu-projectUITests' do
    # Pods for testing
  end

end
